### ISSUE TITLE
[BUG]  Applications gone when migrating from Pawelmalak

### ISSUE THREAD

**Issue by stefaanbolle** [fdarveau/flame#25]
Bug description:
When I overwrite the docker container with this repo, all applications that were configured using the pawelmalak repo are gone.
How can I easy migrate without needing to define all applications links again? I really like the categories possibility in the Applications section.
Bookmarks do get correctly integrated.

**Comment by fdarveau** [comment]
Hello,

To be honest, I would not expect the migration to be perfect since the data model changed between the original project and this fork.

You could try using a SQLite database editor app (such as https://sqlitebrowser.org/) to see if your apps are still there in the `apps` table, but with an empty/null `categoryId`. If they are :
1. Make a backup of the database file.
2. Check in the `categories` table for any app category (`type` = `apps`) you created. Create one if you haven't yet :)
3. Assign that category's `id` to the `app.categoryId` of every app in the `apps` table.
4. Make sure to save/commit the changes.
5. Refresh the flame webpage. 

If the procedure above worked, you should see all your apps in a single category. All you have to do after that is go through the flame UI to create all categories you want and edit the apps in the first category to move them to the correct one.

If the procedure didn't work, it unfortunately means you will need to create apps manually.

If your apps are running under docker/kubernetes, you could try setting it up and adding labels as shown in the README : https://github.com/fdarveau/flame?tab=readme-ov-file#docker-integration

**Comment by stefaanbolle** [comment]
This did the trick, thanks!
